package care.up.enums;

public enum ProfessionType {
	
	INFIRMIER,
	INFIRMIER_EN_ATTENTE,
	KINE,
	KINE_EN_ATTENTE,
	AIDE_SOIGNANTE,
	AIDE_SOIGNANTE_EN_ATTENTE,
	SAGE_FEMME,
	SAGE_FEMME_EN_ATTENTE,
	INFIRMIER_DESACTIVER,
	KINE_DESACTIVER,
	AIDE_SOIGNANTE_DESACTIVER,
	SAGE_FEMME_DESACTIVER,	
	INFIRMIER_ARCHIVER,
	KINE_ARCHIVER,
	AIDE_SOIGNANTE_ARCHIVER,
	SAGE_FEMME_ARCHIVER
}
